import Link from "next/link";
import {
  ArrowRight,
  Webhook,
  BarChart3,
  RefreshCw,
  MessageSquare,
  Snowflake,
  Code,
  Database,
  Server,
  Mail,
} from "lucide-react";

const features = [
  {
    icon: Webhook,
    title: "Webhook Error Interceptor",
    demoPath: "/demo → Webhook Setup",
    clicks: [
      "Copy the webhook URL button",
      "Switch between Make / n8n / Zapier platform tabs",
      "Click 'Send Test Webhook' to simulate an incoming error",
      "View the connected workflows list with status badges",
    ],
    mocked:
      "Webhook URL, test payload delivery, and connected workflow statuses are all client-side simulations. No actual HTTP requests are made.",
    production: `Workflows POST error payloads to \`POST /v1/webhook/:token\`. Server validates HMAC signature, normalizes payload schema, and enqueues to BullMQ. Each customer gets a unique endpoint with rate limiting.`,
    dataFlow: `Make/n8n/Zapier error handler → FlowGuard webhook → BullMQ queue → OpenAI classifier → error_logs table → dashboard update via WebSocket`,
  },
  {
    icon: BarChart3,
    title: "Categorized Failure Dashboard",
    demoPath: "/demo → Failure Dashboard",
    clicks: [
      "Click category summary cards to filter the table",
      "Open the Filters dropdown to filter by category and status",
      "Click the eye icon on any row to open the detail modal",
      "Use 'Retry Now', 'Freeze Workflow', or 'Mark Resolved' in the modal",
    ],
    mocked:
      "All failures, categories, and suggested fixes are hardcoded. Filter and status changes update local React state only.",
    production: `OpenAI classifies each error into categories (timeout, missing_field, rate_limit, auth_error, validation) and generates suggested fixes. Stored in Supabase with full-text search and real-time subscriptions.`,
    dataFlow: `BullMQ worker → OpenAI classification → error_logs insert → Supabase realtime → dashboard re-render`,
  },
  {
    icon: RefreshCw,
    title: "Auto-Retry with Backoff",
    demoPath: "/demo → Auto-Retry",
    clicks: [
      "Adjust sliders for max retries, initial delay, max delay, and backoff multiplier",
      "Toggle which error categories trigger auto-retry",
      "Click 'Save Configuration' to persist settings (toast only)",
      "Click 'Simulate Retry' to watch a live backoff simulation",
      "View the retry history table at the bottom",
    ],
    mocked:
      "Retry config saves to local state only. Simulation is a timed animation. Retry history is static sample data.",
    production: `BullMQ schedules retry jobs with exponential backoff per customer config. Each retry re-invokes the original workflow step via platform API (Make/n8n/Zapier). Dead-letter queue for max retries exceeded.`,
    dataFlow: `Classified error → retry eligible? → BullMQ delayed job → platform API re-invoke → success/fail → update error_logs status`,
  },
  {
    icon: MessageSquare,
    title: "Plain-English Alerts",
    demoPath: "/demo → Alerts",
    clicks: [
      "Filter alerts by All / Slack / Email channel tabs",
      "Click any alert card to view the full message in a modal",
      "Click 'Send Test Alert' to compose and send a test notification",
      "Click 'Preview Weekly Digest' to see the cron-generated summary",
      "Click 'Manage channels' or 'Manage recipients' on notification cards",
    ],
    mocked:
      "Alert content is pre-written sample data. Send/preview actions show toast notifications only. No actual Slack or email delivery.",
    production: `OpenAI generates plain-English summaries from classified errors. Delivered via Slack API (Block Kit messages) and Resend (HTML email). Weekly digest generated by cron job every Monday.`,
    dataFlow: `Error classified → OpenAI plain-English generator → alert_templates render → Slack API / Resend → delivery confirmation logged`,
  },
  {
    icon: Snowflake,
    title: "Freeze & Notify",
    demoPath: "/demo → Freeze & Notify",
    clicks: [
      "Click 'Freeze & Notify' on any workflow row",
      "Confirm in the modal to freeze and trigger owner notification",
      "Click 'Resume' on frozen workflows to unfreeze",
      "Use the Emergency Stop button to freeze/unfreeze all workflows at once",
    ],
    mocked:
      "Freeze/resume updates local workflow state and shows toast notifications. No actual platform API calls to disable scenarios.",
    production: `Calls platform API to disable workflow (Make scenario off, n8n workflow deactivated, Zapier zap off). Sends immediate Slack + email with plain-English explanation. Owner resumes via FlowGuard dashboard which re-enables via platform API.`,
    dataFlow: `User clicks freeze → platform API disable → workflow status update → alert generation → Slack + email → owner fixes issue → resume via FlowGuard → platform API enable`,
  },
];

const architecture = [
  {
    icon: Server,
    label: "Webhook Receiver",
    tech: "Node.js + Express",
    desc: "Receives error payloads, validates signatures, enqueues to BullMQ",
  },
  {
    icon: Database,
    label: "Data Store",
    tech: "Supabase (Postgres)",
    desc: "error_logs, workflows, customers, retry_configs, alert_history",
  },
  {
    icon: Code,
    label: "Classification",
    tech: "OpenAI API",
    desc: "Categorizes errors and generates plain-English explanations + fixes",
  },
  {
    icon: RefreshCw,
    label: "Job Queue",
    tech: "BullMQ + Redis",
    desc: "Retry scheduling, alert delivery, digest generation",
  },
  {
    icon: Mail,
    label: "Notifications",
    tech: "Slack API + Resend",
    desc: "Real-time alerts and weekly digest emails",
  },
];

export default function DevelopersPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="mb-12">
        <h1 className="text-4xl font-bold text-white">Developer Documentation</h1>
        <p className="mt-4 text-lg text-gray-400">
          Everything in the{" "}
          <Link href="/demo" className="text-brand-400 hover:text-brand-300">
            interactive demo
          </Link>{" "}
          maps to a production feature. This page explains what&apos;s mocked,
          what&apos;s real in a future build, and the intended data flow.
        </p>
      </div>

      {/* Architecture overview */}
      <section className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-white">
          Production Architecture
        </h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {architecture.map((item) => (
            <div key={item.label} className="glass-card p-5">
              <item.icon className="mb-3 h-5 w-5 text-brand-400" />
              <h3 className="font-semibold text-white">{item.label}</h3>
              <p className="mt-1 text-xs font-mono text-brand-400">
                {item.tech}
              </p>
              <p className="mt-2 text-sm text-gray-400">{item.desc}</p>
            </div>
          ))}
        </div>
        <div className="mt-6 glass-card p-6">
          <h3 className="mb-3 font-semibold text-white">End-to-End Data Flow</h3>
          <pre className="overflow-x-auto font-mono text-xs leading-relaxed text-gray-400">
{`Workflow Error → Webhook POST → HMAC Validate → BullMQ Enqueue
    → OpenAI Classify → Store in Supabase
    → Branch: Retry eligible? → BullMQ Delayed Retry → Platform API
    → Branch: Critical? → Freeze via Platform API → Alert via Slack/Email
    → Dashboard updates via Supabase Realtime
    → Weekly: Cron → Aggregate → Digest Email via Resend
    → Billing: Stripe Webhook → Update subscription tier`}
          </pre>
        </div>
      </section>

      {/* Feature docs */}
      <section className="mb-16">
        <h2 className="mb-6 text-2xl font-bold text-white">Feature Reference</h2>
        <div className="space-y-8">
          {features.map((feature, i) => (
            <div key={feature.title} className="glass-card p-6">
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-brand-600/20">
                  <feature.icon className="h-5 w-5 text-brand-400" />
                </div>
                <div>
                  <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
                    Feature {i + 1}
                  </span>
                  <h3 className="text-lg font-semibold text-white">
                    {feature.title}
                  </h3>
                </div>
              </div>

              <div className="mb-4">
                <Link
                  href="/demo"
                  className="inline-flex items-center gap-1 text-sm text-brand-400 hover:text-brand-300"
                >
                  Try it: {feature.demoPath}
                  <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </div>

              <div className="space-y-4 text-sm">
                <div>
                  <h4 className="mb-2 font-semibold text-gray-300">
                    What to click in the demo
                  </h4>
                  <ul className="space-y-1">
                    {feature.clicks.map((click) => (
                      <li
                        key={click}
                        className="flex items-start gap-2 text-gray-400"
                      >
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-500" />
                        {click}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 p-4">
                  <h4 className="mb-1 text-xs font-semibold uppercase text-amber-400">
                    What&apos;s mocked
                  </h4>
                  <p className="text-gray-400">{feature.mocked}</p>
                </div>

                <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-4">
                  <h4 className="mb-1 text-xs font-semibold uppercase text-emerald-400">
                    Production implementation
                  </h4>
                  <p className="text-gray-400">{feature.production}</p>
                </div>

                <div className="rounded-lg border border-brand-500/20 bg-brand-500/5 p-4">
                  <h4 className="mb-1 text-xs font-semibold uppercase text-brand-400">
                    Data flow
                  </h4>
                  <p className="font-mono text-xs text-gray-400">
                    {feature.dataFlow}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* DEV NOTE badges */}
      <section className="mb-16">
        <h2 className="mb-4 text-2xl font-bold text-white">DEV NOTE Badges</h2>
        <p className="text-sm text-gray-400">
          Throughout the demo, small{" "}
          <span className="inline-flex items-center gap-1 rounded-full border border-brand-500/30 bg-brand-500/10 px-1.5 py-0.5 text-[10px] font-semibold uppercase text-brand-400">
            DEV
          </span>{" "}
          badges appear beside major controls. Click any badge to see what that
          feature does in production and how it would be implemented. These are
          demo-only annotations and would be removed in the production app.
        </p>
      </section>

      {/* MVP estimate */}
      <section className="glass-card p-6">
        <h2 className="mb-4 text-xl font-bold text-white">MVP Build Estimate</h2>
        <p className="text-sm text-gray-400">
          <strong className="text-gray-300">Stack:</strong> Node.js + Supabase +
          Resend (email) + Slack API; webhook receiver + retry queue via BullMQ
        </p>
        <p className="mt-2 text-sm text-gray-400">
          <strong className="text-gray-300">Timeline:</strong> ~3 weeks to MVP
        </p>
        <p className="mt-2 text-sm text-gray-400">
          <strong className="text-gray-300">Owner maintenance:</strong> ~1
          hour/week reviewing edge-case error classifications
        </p>
        <Link href="/research" className="mt-4 inline-flex items-center gap-1 text-sm text-brand-400 hover:text-brand-300">
          Read the research behind this idea
          <ArrowRight className="h-3.5 w-3.5" />
        </Link>
      </section>
    </div>
  );
}
